export const RECEIVE_SEARCH_RESULT = 'RECEIVE_SEARCH_RESULT';
export const REQUEST_SEARCH_RESULT = 'REQUEST_SEARCH_RESULT';
export const RECEIVE_MOST_SEARCH_RESULT = 'RECEIVE_MOST_SEARCH_RESULT';
export const REQUEST_MOST_SEARCH_RESULT = 'REQUEST_MOST_SEARCH_RESULT';